# Generated by Django 2.1.4 on 2020-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement_brief_tab',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
