# Generated by Django 2.1.4 on 2020-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0004_new_achievement_tab_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_achievement_tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('a_id', models.IntegerField()),
            ],
            options={
                'db_table': 'collect_achievement_tab',
            },
        ),
        migrations.CreateModel(
            name='collect_scholar_tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('scholar_id', models.IntegerField()),
            ],
            options={
                'db_table': 'collect_scholar_tab',
            },
        ),
        migrations.CreateModel(
            name='scholar_department_tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scholar_id', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
            options={
                'db_table': 'scholar_department_tab',
            },
        ),
        migrations.CreateModel(
            name='student_achievement_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('a_id', models.IntegerField()),
            ],
            options={
                'db_table': 'student_achievement_tab',
            },
        ),
        migrations.CreateModel(
            name='student_department_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
            options={
                'db_table': 'student_department_tab',
            },
        ),
        migrations.RemoveField(
            model_name='user_authen_tab',
            name='u_id',
        ),
        migrations.AddField(
            model_name='achievementtab',
            name='keyword',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='new_achievement_tab',
            name='keyword',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='scholartab',
            name='Flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholartab',
            name='Scholar_Number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievementauthentab',
            name='a_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementauthentab',
            name='author_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementauthentab',
            name='file',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementauthentab',
            name='j_a_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementauthentab',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementtab',
            name='author_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementtab',
            name='file',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementtab',
            name='j_a_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementtab',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementtab',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_achievement_tab',
            name='file',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_achievement_tab',
            name='j_a_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_achievement_tab',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_achievement_tab',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_achievement_tab',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scholarachievementtab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scholartab',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_authen_tab',
            name='authen_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_tab',
            name='authority',
            field=models.SmallIntegerField(choices=[(0, '普通用户'), (1, '学者用户'), (2, '学生用户')], default=0),
        ),
    ]
