# Generated by Django 2.1.4 on 2020-05-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0005_auto_20200517_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholartab',
            old_name='Flag',
            new_name='flag',
        ),
    ]
