# Generated by Django 2.1.4 on 2020-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0006_auto_20200517_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementtab',
            name='kind',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
