# Generated by Django 2.1.4 on 2020-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0007_achievementtab_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementtab',
            name='num_view',
            field=models.IntegerField(default=0),
        ),
    ]
